# Generated by Django 5.2.4 on 2025-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_currency_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='current_entry_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
